# Generated by Django 4.1.7 on 2023-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen_url', models.TextField()),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
